### ISSUE TITLE
Invoice Service Not running

### ISSUE THREAD

**Issue by francoisdutoit** [vany0114/microservices-dotnetcore-docker-servicefabric#1]
Hi , Thanks so much for this article - really learned allot. I have tried deploying a couple of time but my invoice service just does not want to work in Azure. And the error message does not provide much details...any suggestions? See below screenshot

Thanks in advance!

![image](https://user-images.githubusercontent.com/9386768/43687266-6b868a38-98d2-11e8-85f5-8f4d28427bb0.png)

**Comment by francoisdutoit** [comment]
PS : I know it says "in Build" but I have left it for long and it does not correct.

**Comment by vany0114** [comment]
Hi @francoisdutoit did you change some configuration in the `ApplicationManifest`? if so, can you show me that file, please?

**Comment by francoisdutoit** [comment]
Here is the ApplicationMaifest...
<?xml version="1.0" encoding="utf-8"?>
<ApplicationManifest ApplicationTypeName="DuberMicroservicesType"
                     ApplicationTypeVersion="1.0.0"
                     xmlns="http://schemas.microsoft.com/2011/01/fabric"
                     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Parameters>
    <Parameter Name="Invoice_InstanceCount" DefaultValue="-1" />
    <Parameter Name="Trip_InstanceCount" DefaultValue="-1" />
  </Parameters>
  
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="InvoicePkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="Code">
        <PortBinding ContainerPort="80" EndpointRef="InvoiceTypeEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="TripPkg" ServiceManifestVersion="1.0.0" />
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="Code">
        <PortBinding ContainerPort="80" EndpointRef="TripTypeEndpoint" />
      </ContainerHostPolicies>
    </Policies>
  </ServiceManifestImport>
  <DefaultServices>
    
    <Service Name="Invoice" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="InvoiceType" InstanceCount="[Invoice_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
    <Service Name="Trip" ServicePackageActivationMode="ExclusiveProcess">
      <StatelessService ServiceTypeName="TripType" InstanceCount="[Trip_InstanceCount]">
        <SingletonPartition />
      </StatelessService>
    </Service>
  </DefaultServices>
</ApplicationManifest>

**Comment by francoisdutoit** [comment]
And the Invoice ServiceManifest...

`<?xml version="1.0" encoding="utf-8"?>
<ServiceManifest Name="InvoicePkg"
                 Version="1.0.0"
                 xmlns="http://schemas.microsoft.com/2011/01/fabric"
                 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <ServiceTypes>
    
    <StatelessServiceType ServiceTypeName="InvoiceType" UseImplicitHost="true" />
  </ServiceTypes>

  
  <CodePackage Name="Code" Version="1.0.0">
    <EntryPoint>
      
      <ContainerHost>
        <ImageName>memememe/duber.invoice.api:prod</ImageName>
      </ContainerHost>
    </EntryPoint>
    
    <EnvironmentVariables>
      <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value="Production"/>
      <EnvironmentVariable Name="ASPNETCORE_URLS" Value="http://0.0.0.0:80"/>
      <EnvironmentVariable Name="ConnectionString" Value="Server=tcp:dubersql.database.windows.net,1433;Initial Catalog=Duber.InvoiceDb;Persist Security Info=False;User ID=THEUSER;Password=MYPASSWORD;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"/>
      <EnvironmentVariable Name="EventBusConnection" Value="Endpoint=sb://dubersb.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=MYKEY"/>
      <EnvironmentVariable Name="AzureServiceBusEnabled" Value="True"/>
      <EnvironmentVariable Name="PaymentServiceBaseUrl" Value="https://paymentservice.azurewebsites.net"/>
    </EnvironmentVariables>
  </CodePackage>

  
  <ConfigPackage Name="Config" Version="1.0.0" />

  <Resources>
    <Endpoints>
      
      <Endpoint Name="InvoiceTypeEndpoint" Port="5101" />
    </Endpoints>
  </Resources>
</ServiceManifest>`

**Comment by vany0114** [comment]
Can you show me the `ApplicationParameters/Cloud.xml` or tell me the number of instances you have configured there when you did the deploy, please

**Comment by vany0114** [comment]
I thought you had more instances than nodes for Invoice microservice, that's a common error when you have a singleton partition. But that's odd since the Trip microservice is working fine. Try to look into logs at nodes level, I can see that `primary0 `and `primary4` seems to be successfully deployed.
